package main

import (
	"encoding/base64"
	"flag"
	"kms/pkg/encryption"
	"log"
)

func main() {
	var nBytes int

	flag.IntVar(&nBytes, "n", 32, "number of bytes")

	flag.Parse()

	bytes, err := encryption.GenerateKey(nBytes)
	if err != nil {
		log.Fatalf("unexpected error: %v", err)
	}

	log.Printf("generated bytes: %s", base64.RawURLEncoding.EncodeToString(bytes))
}
